name: "rss-to-issues"
author: "Johannes Schindelin, Guilhem Lettron"
description: "Create Issues from RSS/Atom feeds"
branding:
  icon: "rss"
  color: "orange"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
  feed:
    description: "URL of the RSS/Atom feed"
  prefix:
    description: "Prefix added to the created issues' titles"
  lastTime:
    description: "limit RSS items to this time"
  labels:
    description: "Labels to add, comma separated"
  dry-run:
    description: "Log issue creation but do nothing"
  aggregate:
    description: "Aggregate all items in a single issue"
  characterLimit:
    description: "Limit size of issue content"
  titleFilter:
    description: "Filter out entries whose titles match this regex"
  contentFilter:
    description: "Filter out entries whose contents match this regex"
outputs:
  issues:
    description: "issue IDs, comma separated"
runs:
  using: "docker"
  image: "Dockerfile"
